### ISSUE TITLE
Task 关联多个 会执行多次 execute

### ISSUE THREAD

**Issue by yuxiaobi** [wangchenyan/init#2]
Task 关联多个 会执行多次 execute  会进行多次初始化

**Comment by wangchenyan** [comment]
你好，关联多个是什么意思，有代码吗？

**Comment by yuxiaobi** [comment]
![image](https://user-images.githubusercontent.com/23207216/174566859-24cf4928-78cc-42f5-9e50-20285fec9860.png)
MainTask2 初始化两次

**Comment by wangchenyan** [comment]
@yuxiaobi 麻烦看下是不是在两个进程分别初始化了，有一个service是在core进程启动的
